// 盛诗博的Web前端学习系统大全/Demo19_Vue/code/mozhi_vue_demo/src/views/Home.vue
<template>
  <div>
    <h2>Home</h2>
    <div>
      <ul class="nav nav-tabs">
        <li>
          <router-link to="/home/news">News</router-link>
          <router-link to="/home/message">Messages</router-link>
        </li>
      </ul>
      <div>
        <router-view></router-view>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  
}
</script>

<style>
  
</style>

// 盛诗博的Web前端学习系统大全/Demo18_React/code/react_router_demo/src/views/home.jsx
import React, {Component} from 'react'
import {Switch, Route, Redirect} from 'react-router-dom'

import MyNavLink from '../components/myNavLink'
import News from '../views/news'
import Message from '../views/message'

export default class Home extends Component {
  render () {
    return (
      <div>
        <h2>home router Component</h2>
        <div>
          <ul className='nav nav-tabs'>
            <li>
              <MyNavLink to='/home/news'>News</MyNavLink>
            </li>
            <li>
              <MyNavLink to='/home/message'>Message</MyNavLink>
            </li>
          </ul>
          <div>
            <Switch>
              <Route path='/home/news' component={News} />
              <Route path='/home/message' component={Message} />
              <Redirect to='/home/news' />
            </Switch>
          </div>
        </div>
      </div>
    )
  }
}
