// 盛诗博的Web前端学习系统大全/Demo19_Vue/code/mozhi_vue_demo/src/views/Message.vue
<template>
  <div>
    <ul>
      <li v-for="message in messages" :key="message.id">
        <!-- <a href="???">{{message.title}}</a> -->
        <router-link :to="`/home/message/detail/${message.id}`">{{message.title}}</router-link>
        <button @click="pushShow(message.id)">Push查看</button>
        <button @click="replaceShow(message.id)">Replace查看</button>
      </li>
    </ul>
    <button @click="$router.back()">回退</button>
    <hr>
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  data () {
    return {
      messages: []
    }
  },
  mounted() {
    // 模拟ajax请求从后台获取数据
    setTimeout(() => {
      const messages = [
        {
          id: '1',
          title: 'message001'
        },
        {
          id: '2',
          title: 'message002'
        },
        {
          id: '3',
          title: 'message003'
        },
        {
          id: '4',
          title: 'message004'
        }
      ]
      this.messages = messages
    }, 1000)
  },
  methods: {
    pushShow (id) {
      this.$router.push(`/home/message/detail/${id}`)
    },
    replaceShow (id) {
      this.$router.replace(`/home/message/detail/${id}`)
    }
  }
}
</script>

<style>
  
</style>

// 盛诗博的Web前端学习系统大全/Demo18_React/code/react_router_demo/src/views/message.jsx
import React, {Component} from 'react'
import {Route} from 'react-router-dom'

import MessageDetail from '../views/message-detail'
import MyNavLink from '../components/myNavLink';

export default class message extends Component {

  state = {
    messages: [
      // {id: 1, title: 'message001'},
      // {id: 3, title: 'message003'},
      // {id: 5, title: 'message005'}
    ]
  }

  componentDidMount () {
    // 模拟发送ajax请求异步获取数据
    setTimeout(() => {
      const messages = [
        {id: 1, title: 'message001'},
        {id: 3, title: 'message003'},
        {id: 5, title: 'message005'}
      ]
      // 更新状态
      this.setState({messages})
    }, 1000);
  }

  showDetail = (id) => {
    this.props.history.push(`/home/message/messagedetail/${id}`)
  }
  showDetail2 = (id) => {
    this.props.history.replace(`/home/message/messagedetail/${id}`)
  }
  back = () => {
    this.props.history.goBack()
  }
  forward = () => {
    this.props.history.goForward()
  }
  reqPage = () => {
    // 通过js进行页面跳转
    // 注意一点是，路由跳转没有发送请求，而页面跳转就会发送
    window.location = 'www.baidu.com'
  }

  render () {
    return (
      <div>
        <ul>
          {
            this.state.messages.map((message, index) => (
              <li key={index}>
                {/* <a href={`/home/message/messagedetail/${message.id}`}>{message.title}</a> */}
                <MyNavLink to={`/home/message/messagedetail/${message.id}`}>{message.title}</MyNavLink>
                &nbsp;&nbsp;<button onClick={() => {this.showDetail(message.id)}}>push()查看</button>
                &nbsp;&nbsp;<button onClick={() => {this.showDetail2(message.id)}}>replace()查看</button>
              </li>
            ))
          }
        </ul>
        <p>
          <button onClick={this.back}>回退</button>
          <button onClick={this.forward}>前进</button>
        </p>
        <p>
          <button onClick={this.reqPage}>页面跳转</button>
        </p>
        <Route path='/home/message/messagedetail/:id' component={MessageDetail} />
      </div>
    )
  }
}
