// 盛诗博的Web前端学习系统大全/Demo19_Vue/code/mozhi_vue_demo/src-comments/App.vue
<template>
  <div>
    <header class="site-header jumbotron">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h1>请发表对Vue的评论</h1>
          </div>
        </div>
      </div>
    </header>
    <div class="container">
      <Add :addComments='addComments'/>
      <List :comments="comments" :deleteItem="deleteItem"/>
    </div>
  </div>
</template>

<script>
  import Add from './components/Add'
  import List from './components/List'
  export default {
    data () {
      return {
        comments: [
          {name: 'mozhi', content: 'Vue 很好学'},
          {name: 'yangyang', content: 'Vue 太简单了'},
          {name: 'wanghenan', content: '很好'}
        ]
      }
    },
    methods: {
      // 添加评论
      addComments (comment) {
        this.comments.unshift(comment)
      },
      // 删除指定下标的评论
      deleteItem (index) {
        this.comments.splice(index, 1)
      }
    },
    components: {
      Add,
      List
    }
  }
</script>

<style>
  
</style>

// 盛诗博的Web前端学习系统大全/Demo18_React/code/react_redux_demo/src/containers/app/app.jsx
import React from 'react'
import PropTypes from 'prop-types'
import {connect} from 'react-redux'

import CommentAdd from '../../components/comment-add/comment-add'
import CommentList from '../../components/comment-list/comment-list'
import {addComment, deleteComment, getComments} from '../../redux/actions'

class App extends React.Component {

  static propTypes = {
    comments: PropTypes.array.isRequired,
    addComment: PropTypes.func.isRequired,
    deleteComment: PropTypes.func.isRequired,
    getComments: PropTypes.func.isRequired
  }

  componentDidMount () {
    // 异步获取评论数组
    this.props.getComments()
  }

  render () {

    const {comments, addComment, deleteComment} = this.props

    return (
      <div>
        <header className="site-header jumbotron">
          <div className="container">
            <div className="row">
              <div className="col-xs-12">
                <h1>请发表对React的评论</h1>
              </div>
            </div>
          </div>
        </header>
        <div className="container">
          <CommentAdd add={addComment}/>
          <CommentList comments={comments} delete={deleteComment}/>
        </div>
      </div>
    )
  }
}

export default connect(
  state => ({
    comments: state
  }),
  {addComment, deleteComment, getComments}
)(App)
