// 盛诗博的Web前端学习系统大全/Demo19_Vue/code/mozhi_vue_demo/src-comments/App.vue
<template>
  <div>
    <header class="site-header jumbotron">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h1>请发表对Vue的评论</h1>
          </div>
        </div>
      </div>
    </header>
    <div class="container">
      <Add :addComments='addComments'/>
      <List :comments="comments" :deleteItem="deleteItem"/>
    </div>
  </div>
</template>

<script>
  import Add from './components/Add'
  import List from './components/List'
  export default {
    data () {
      return {
        comments: [
          {name: 'mozhi', content: 'Vue 很好学'},
          {name: 'yangyang', content: 'Vue 太简单了'},
          {name: 'wanghenan', content: '很好'}
        ]
      }
    },
    methods: {
      // 添加评论
      addComments (comment) {
        this.comments.unshift(comment)
      },
      // 删除指定下标的评论
      deleteItem (index) {
        this.comments.splice(index, 1)
      }
    },
    components: {
      Add,
      List
    }
  }
</script>

<style>
  
</style>

// 盛诗博的Web前端学习系统大全/Demo18_React/code/custom_react_demo/src/components/app/app.jsx
import React, {Component} from 'react'
import CommentAdd from '../comment-add/comment-add'
import ComentList from '../comment-list/comment-list'

export default class App extends Component {

  constructor (props) {
    super(props)
    // this.state = {
    //   comments: [
    //     {username: 'Tom', content: 'React挺好的'},
    //     {username: 'Jack', content: 'React太难了'}
    //   ]
    // }
  }

  // 给组件对象指定state属性
  state = {
    comments: [
      {username: 'Tom', content: 'React挺好的'},
      {username: 'Jack', content: 'React太难了'}
    ]
  }

  // 添加评论
  addComment = (comment) => {
    const {comments} = this.state
    comments.unshift(comment)
    // 更新状态
    this.setState({comments})
  }

  // 删除评论
  deleteComment = (index) => {
    const {comments} = this.state
    comments.splice(index, 1)
    // 更新状态
    this.setState({comments})
  }

  render () {

    const {comments} = this.state

    return (
      <div>
        <header className="site-header jumbotron">
          <div className="container">
            <div className="row">
              <div className="col-xs-12">
                <h1>请发表对React的评论</h1>
              </div>
            </div>
          </div>
        </header>
        <div className="container">
          <CommentAdd addComment={this.addComment} />
          <ComentList comments={comments} deleteComment={this.deleteComment} />
        </div>
      </div>
    )
  }
}
