// 盛诗博的Web前端学习系统大全/Demo18_React/code/react_redux_demo/src_counter1_react/components/app.jsx
import React, {Component} from 'react'

export default class App extends Component {

  state = {
    count: 0
  }

  increment = () => {
    // 1. 得到选择增加的数量
    const number = this.select.value * 1
    // 2. 得到原本的count状态，并计算新的count
    const count = this.state.count + number
    // 3. 更新状态
    this.setState({count})
  }

  decrement = () => {
    // 1. 得到选择增加的数量
    const number = this.select.value * 1
    // 2. 得到原本的count状态，并计算新的count
    const count = this.state.count - number
    // 3. 更新状态
    this.setState({count})
  }
  incrementIfOdd = () => {
    // 1. 得到选择增加的数量
    const number = this.select.value * 1
    // 2. 得到原本的count状态
    const count = this.state.count
    // 判断，满足条件才更新状态
    if (count % 2 === 1) {
      // 3. 更新状态
      this.setState({count: count + number})
    }
    
  }

  incrementAsync = () => {
    // 1. 得到选择增加的数量
    const number = this.select.value * 1
    // 2. 得到原本的count状态
    const count = this.state.count
    // 启动延时定时器
    setTimeout(() => {
      // 3. 更新状态
      this.setState({count: count + number})
    }, 1000);
  }

  render () {
    return (
      <div>
        <p>click {this.state.count} times</p>
        <div>
          <select ref={select => this.select = select}>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
          </select>&nbsp;
          <button onClick={this.decrement}>-</button>&nbsp;
          <button onClick={this.increment}>+</button>&nbsp;
          <button onClick={this.incrementIfOdd}>increment if odd</button>&nbsp;
          <button onClick={this.incrementAsync}>increment async</button>&nbsp;
        </div>
      </div>
    )
  }
}

// 盛诗博的Web前端学习系统大全/Demo19_Vue/code/mozhi_vuex_demo2/src-demo1/App.vue
<template>
  <div>
    <p>click {{$store.state.count}} times, count is {{evenOrOdd}}</p>
    <button @click="increment">+</button>
    <button @click="decrement">-</button>
    <button @click="incrementIfOdd">increment if odd</button>
    <button @click="incrementAsync">increment async</button>
  </div>
</template>

<script>
  import {mapState, mapGetters, mapActions} from 'vuex'
  export default {
    data () {
      return {
        // count: 0
      }
    },
    computed: {
      // evenOrOdd () {
      //   return this.$store.getters.evenOrOdd
      // }
      ...mapState(['count']),
      ...mapGetters(['evenOrOdd'])
    },
    methods: {
      ...mapActions(['increment', 'decrement', 'incrementIfOdd', 'incrementAsync'])
    }
    // methods: {
    //   increment () {
    //     this.$store.dispatch('increment')
    //   },
    //   decrement () {
    //     this.$store.dispatch('decrement')
    //   },
    //   incrementIfOdd () {
    //     this.$store.dispatch('incrementIfOdd')
    //   },
    //   incrementAsync () {
    //     this.$store.dispatch('incrementAsync')
    //   }
    // }
  }
</script>

<style>

</style>
